### ISSUE TITLE
iOS app shouldn’t allow posting of completely empty posts

### ISSUE THREAD

**Issue by sardisson** [microdotblog/issues#134]
I just opened the posting view and immediately accidentally touched the “Post” button (which is in the same location as the “open posting view” (speech bubble) button in the Timeline views), and Micro.blog happily sent off a completely empty post to my blog.

It would be nice if the “Post” button were disabled until an image or a character of text were added to the post, or if the app checked for an image or a character of text _after_ “Post” was pressed but _before_ submitting to a blog (I don’t know the behind-the-scenes flow involved to know if this is possible and/or which option might be preferable).

It is also possible to submit an empty reply, but it requires more effort (deleting the prefilled @-name, as when you are going to make a post-like reply to a titled post, for instance) and is thus harder to do accidentally. One may, however, want to check for the presence of a non-space character of text that is not part of an @-name, to prevent an accidental @-name-only reply….

**Comment by issimonwoods** [comment]
You now get an error message when attempting to publish an empty post.

Fixed yeah?

**Comment by paulrobertlloyd** [comment]
Possibly fixed in earlier releases, but also not an issue in 3.0. You get a warning if trying to post with not content.

**Comment by paulrobertlloyd** [comment]
> It would be nice if the “Post” button were disabled until an image or a character of text were added to the post

In 3.0, post button still shows as active, if pressing it would show an error. This feels counter intuitive.
